<a href="https://colab.research.google.com/github/Danylo5051/machine-learning-lectures4-9/blob/main/%D0%A1%D0%B0%D1%82%D0%BA%D0%BE%D0%94_%D0%BB%D0%B5%D0%BA%D1%86_%D1%82%D1%80%D0%B5%D0%BD_%D0%BD%D0%BE%D1%83%D1%82_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

print("NumPy version:" , np.__version__)

NumPy version: 2.1.3


In [4]:
a = np.array([1, 2, 3, 4, 5], dtype=np.float64)

m = np.array([
    [1, 2, 3],
    [4, 5, 6]
], dtype=np.int64)

print("Вектор a:")
print(a)

print("\nМатриця M:")
print(m)

Вектор a:
[1. 2. 3. 4. 5.]

Матриця M:
[[1 2 3]
 [4 5 6]]


In [5]:
print("shape:", m.shape)
print("ndim:", m.ndim)
print("size:", m.size)
print("dtype:", m.dtype)
print("itemsize:", m.itemsize)
print("nbytes:", m.nbytes)

shape: (2, 3)
ndim: 2
size: 6
dtype: int64
itemsize: 8
nbytes: 48


Самостійно
Створіть матрицю розміру (3, 4) та перевірте її shape, ndim, size, dtype і nbytes.




In [6]:
m = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
], dtype=np.int64)

print("Матриця M:")
print(m)
print()
print("shape:", m.shape)
print("ndim:", m.ndim)
print("size:", m.size)
print("dtype:", m.dtype)
print("itemsize:", m.itemsize)
print("nbytes:", m.nbytes)

Матриця M:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

shape: (3, 4)
ndim: 2
size: 12
dtype: int64
itemsize: 8
nbytes: 96


3. Спеціальні функції створення масивів

In [7]:
a = np.array([1, 2, 3, 4])
zeros = np.zeros((2, 3), dtype=np.float32)
ones = np.ones((2, 3), dtype=np.int64)
full = np.full((2, 3), 7)
I = np.eye(4)

print("a =", a)
print("\nzeros =\n", zeros)
print("\nones =\n", ones)
print("\nfull =\n", full)
print("\nI =\n", I)

a = [1 2 3 4]

zeros =
 [[0. 0. 0.]
 [0. 0. 0.]]

ones =
 [[1 1 1]
 [1 1 1]]

full =
 [[7 7 7]
 [7 7 7]]

I =
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


arange і linspace

In [8]:
x1 = np.arange(0, 1, 0.2)
x2 = np.linspace(0, 1, num=6)

print("arange:", x1)
print("linspace:", x2)

arange: [0.  0.2 0.4 0.6 0.8]
linspace: [0.  0.2 0.4 0.6 0.8 1. ]


np.arange(start, stop, step) зручний, коли задається крок.
np.linspace(start, stop, num) зручний, коли потрібно отримати точно задану кількість рівновіддалених значень.

4. Типи даних dtype

In [9]:
x = np.array([1, 2, 3], dtype=np.int32)
y = x.astype(np.float32)

print("x.dtype:", x.dtype)
print("y.dtype:", y.dtype)

x.dtype: int32
y.dtype: float32


Приклад змішаних типів

In [10]:
a = np.array([1, 2, 3], dtype=np.float32)
b = np.float64(0.5)
c = a + b

print(c)
print("dtype результату:", c.dtype)

[1.5 2.5 3.5]
dtype результату: float64


Самостійно
Створіть масив типу float64 і перетворіть його на float32. Порівняйте itemsize і nbytes.

In [11]:
a = np.array([1, 2, 3, 4], dtype=np.float64)
b = a.astype(np.float32)

print("a.itemsize:", a.itemsize)
print("a.nbytes:", a.nbytes)

print("\nb.itemsize:", b.itemsize)
print("b.nbytes:", b.nbytes)

a.itemsize: 8
a.nbytes: 32

b.itemsize: 4
b.nbytes: 16


5. Індексація та зрізи

In [12]:
a = np.array([10, 20, 30, 40, 50])

print(a[0])
print(a[-1])
print(a[1:4])
print(a[::2])

M = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("\nM[1, 1] =", M[1, 1])
print("M[1:, 1] =", M[1:, 1])
print("M[0, :2] =", M[0, :2])

10
50
[20 30 40]
[10 30 50]

M[1, 1] = 5
M[1:, 1] = [5 8]
M[0, :2] = [1 2]


Булева індексація

In [13]:
scores = np.array([56, 82, 91, 47, 73])
mask = scores >= 60

print("mask:", mask)
print("scores[mask]:", scores[mask])

passed = scores[scores >= 60]
print("passed:", passed)

mask: [False  True  True False  True]
scores[mask]: [82 91 73]
passed: [82 91 73]


Розширена (fancy) індексація

In [14]:
a = np.array([10, 20, 30, 40, 50])
idx = np.array([4, 0, 2])

print(a[idx])

[50 10 30]


Самостійно
Із масиву scores виберіть лише значення від 70 до 90 включно.

In [16]:
scores = np.array([56, 82, 91, 47, 73])

passed = scores[(scores >= 70) & (scores <= 90)]

print("passed:", passed)

passed: [82 73]


6. Представлення (view) та копія

In [17]:
a = np.array([1, 2, 3, 4, 5])

view = a[1:4]
view[0] = 99

print("Після зміни view:")
print("a =", a)
print("view =", view)

a = np.array([1, 2, 3, 4, 5])

copy = a[1:4].copy()
copy[0] = 99

print("\nПісля зміни copy:")
print("a =", a)
print("copy =", copy)

Після зміни view:
a = [ 1 99  3  4  5]
view = [99  3  4]

Після зміни copy:
a = [1 2 3 4 5]
copy = [99  3  4]


Базовий зріз часто повертає view, тому зміна зрізу може змінити вихідний масив.
Якщо потрібні незалежні дані, використовуйте .copy().

7. Векторизація та універсальні функції

In [18]:
values = [1, 2, 3, 4]

# Python
squared_loop = [x ** 2 for x in values]

# NumPy
a = np.array(values)
squared_numpy = a ** 2

print("Python:", squared_loop)
print("NumPy:", squared_numpy)

Python: [1, 4, 9, 16]
NumPy: [ 1  4  9 16]


Поелементний і матричний добутки

In [19]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("a + b =", a + b)
print("a * b =", a * b)
print("a @ b =", a @ b)

a + b = [5 7 9]
a * b = [ 4 10 18]
a @ b = 32


Універсальні функції ufunc

In [20]:
x = np.array([1.0, 4.0, 9.0])

print("sqrt:", np.sqrt(x))
print("log:", np.log(x))
print("maximum:", np.maximum(x, 5.0))

sqrt: [1. 2. 3.]
log: [0.         1.38629436 2.19722458]
maximum: [5. 5. 9.]


8. Broadcasting

In [21]:
X = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

bias = np.array([10, 20, 30])

print("X.shape:", X.shape)
print("bias.shape:", bias.shape)
print("\nX + bias =\n", X + bias)

X.shape: (2, 3)
bias.shape: (3,)

X + bias =
 [[11 22 33]
 [14 25 36]]


Стандартизація за стовпцями через broadcasting

In [22]:
X = np.array([
    [170., 65.],
    [180., 80.],
    [160., 55.]
])

mean = X.mean(axis=0)
std = X.std(axis=0)
X_scaled = (X - mean) / std

print("mean:", mean)
print("std:", std)
print("\nX_scaled =\n", X_scaled)

mean: [170.          66.66666667]
std: [ 8.16496581 10.27402334]

X_scaled =
 [[ 0.         -0.16222142]
 [ 1.22474487  1.29777137]
 [-1.22474487 -1.13554995]]


Самостійно
До кожного стовпця матриці додайте різне число за допомогою broadcasting.

In [24]:
X = np.array([
    [170., 65.],
    [180., 80.],
    [160., 55.]
])

values_to_add = np.array([10., 100.])

X_result = X + values_to_add

print("values_to_add:", values_to_add)
print("\nX_result =\n", X_result)

values_to_add: [ 10. 100.]

X_result =
 [[180. 165.]
 [190. 180.]
 [170. 155.]]


9. Агрегування та параметр axis

In [25]:
M = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("sum:", M.sum())
print("sum(axis=0):", M.sum(axis=0))
print("sum(axis=1):", M.sum(axis=1))
print("mean(axis=0):", M.mean(axis=0))

sum: 21
sum(axis=0): [5 7 9]
sum(axis=1): [ 6 15]
mean(axis=0): [2.5 3.5 4.5]


Робота з NaN

In [26]:
x = np.array([10.0, np.nan, 30.0, 40.0])

print("np.mean(x):", np.mean(x))
print("np.nanmean(x):", np.nanmean(x))

np.mean(x): nan
np.nanmean(x): 26.666666666666668


Корисні агрегувальні функції: sum, mean, median, std, var, min, max, argmin, argmax, quantile, percentile.

10. Зміна форми масивів

In [27]:
a = np.arange(12)
M = a.reshape(3, 4)

print("M =\n", M)
print("\nM.T =\n", M.T)
print("\nravel:", M.ravel())
print("flatten:", M.flatten())

M =
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

M.T =
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

ravel: [ 0  1  2  3  4  5  6  7  8  9 10 11]
flatten: [ 0  1  2  3  4  5  6  7  8  9 10 11]


Додавання нової осі

In [28]:
x = np.array([1, 2, 3])

row = x[np.newaxis, :]
col = x[:, np.newaxis]

print("x.shape:", x.shape)
print("row.shape:", row.shape)
print("col.shape:", col.shape)

print("\nrow =\n", row)
print("\ncol =\n", col)

x.shape: (3,)
row.shape: (1, 3)
col.shape: (3, 1)

row =
 [[1 2 3]]

col =
 [[1]
 [2]
 [3]]


11. Об’єднання масивів

In [29]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print("concatenate axis=0:\n", np.concatenate([a, b], axis=0))
print("\nconcatenate axis=1:\n", np.concatenate([a, b], axis=1))
print("\nvstack:\n", np.vstack([a, b]))
print("\nhstack:\n", np.hstack([a, b]))

concatenate axis=0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

concatenate axis=1:
 [[1 2 5 6]
 [3 4 7 8]]

vstack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

hstack:
 [[1 2 5 6]
 [3 4 7 8]]


stack створює нову вісь

In [30]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

S = np.stack([x, y], axis=0)

print(S)
print("shape:", S.shape)

[[1 2 3]
 [4 5 6]]
shape: (2, 3)


12. Випадкові числа: сучасний Generator API

In [31]:
rng = np.random.default_rng(seed=42)

uniform = rng.random(5)
normal = rng.normal(loc=0.0, scale=1.0, size=5)
integers = rng.integers(0, 10, size=5)

print("uniform:", uniform)
print("normal:", normal)
print("integers:", integers)

uniform: [0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]
normal: [-1.30217951  0.1278404  -0.31624259 -0.01680116 -0.85304393]
integers: [5 3 1 9 7]


Перемішування та випадкова вибірка

In [32]:
rng = np.random.default_rng(123)

idx = np.arange(10)
rng.shuffle(idx)

sample = rng.choice(np.arange(100), size=5, replace=False)

print("shuffled idx:", idx)
print("sample:", sample)

shuffled idx: [7 4 0 2 1 5 6 8 3 9]
sample: [77 43 90 27 44]


Самостійно
Згенеруйте:

матрицю (4, 3) із нормального розподілу;
10 випадкових цілих чисел від 1 до 100;
випадкову вибірку з 5 різних індексів із діапазону 0..19.

In [33]:
rng = np.random.default_rng()

mat_normal = rng.normal(loc=0.0, scale=1.0, size=(4, 3))

integers = rng.integers(1, 101, size=10)

sample = rng.choice(np.arange(20), size=5, replace=False)

print("Матриця normal:\n", mat_normal)
print("\nintegers:", integers)
print("sample:", sample)

Матриця normal:
 [[ 0.39520675 -0.18695701  0.98667733]
 [-0.18381429 -0.17169909 -0.69614986]
 [ 0.10512759  0.57425093  0.47756543]
 [ 0.80550246 -0.07431696  0.45283981]]

integers: [31 15 87 68 74 90 38 27 98 32]
sample: [18  6 15 16  8]


13. Лінійна алгебра
Матричний добуток

In [34]:
A = np.array([
    [1, 2, 3],
    [0, 1, 2]
])

B = np.array([
    [ 1, 2],
    [ 0, 4],
    [-1, 0]
])

C = A @ B
print(C)

[[-2 10]
 [-2  4]]


Діагональ, транспонування та визначник

In [35]:
A = np.array([
    [ 1.,  0., 3.],
    [-1., -1., 2.],
    [ 4.,  7., 2.]
])

print("diag:", np.diag(A))
print("\nA.T =\n", A.T)

det = np.linalg.det(A)
print("\ndet(A) =", det)
print("det близький до -25:", np.isclose(det, -25.0))

diag: [ 1. -1.  2.]

A.T =
 [[ 1. -1.  4.]
 [ 0. -1.  7.]
 [ 3.  2.  2.]]

det(A) = -24.999999999999996
det близький до -25: True


Розв’язання системи Ax = b

In [36]:
A = np.array([
    [1.,  2.,  5.],
    [1., -1.,  3.],
    [3., -6., -1.]
])

b = np.array([-9., 2., 25.])

x = np.linalg.solve(A, b)

print("x =", x)
print("Перевірка A @ x ≈ b:", np.allclose(A @ x, b))

x = [ 2. -3. -1.]
Перевірка A @ x ≈ b: True


Для розв’язання системи не потрібно явно обчислювати A⁻¹.
У числових обчисленнях перевага надається np.linalg.solve(A, b).

Метод найменших квадратів

In [37]:
X = np.array([
    [1., 1.],
    [1., 2.],
    [1., 3.],
    [1., 4.]
])

y = np.array([2.1, 3.9, 6.2, 8.1])

beta, residuals, rank, s = np.linalg.lstsq(X, y, rcond=None)

print("beta:", beta)
print("residuals:", residuals)
print("rank:", rank)
print("singular values:", s)

beta: [6.9423189e-16 2.0300000e+00]
residuals: [0.043]
rank: 2
singular values: [5.77937881 0.77380911]


Власні значення та власні вектори

In [38]:
A = np.array([
    [2., 1.],
    [1., 2.]
])

values, vectors = np.linalg.eigh(A)

print("Власні значення:", values)
print("Власні вектори:\n", vectors)

Власні значення: [1. 3.]
Власні вектори:
 [[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]


SVD

In [39]:
A = np.array([
    [3., 1.],
    [1., 3.],
    [1., 1.]
])

U, s, Vt = np.linalg.svd(A, full_matrices=False)

print("U =\n", U)
print("\ns =", s)
print("\nVt =\n", Vt)

U =
 [[-6.66666667e-01  7.07106781e-01]
 [-6.66666667e-01 -7.07106781e-01]
 [-3.33333333e-01  5.92577380e-18]]

s = [4.24264069 2.        ]

Vt =
 [[-0.70710678 -0.70710678]
 [ 0.70710678 -0.70710678]]


14. NumPy у задачах машинного навчання
14.1. Стандартизація ознак

In [40]:
X = np.array([
    [170., 65., 25.],
    [180., 80., 31.],
    [160., 55., 22.],
    [175., 72., 28.]
])

mu = X.mean(axis=0)
sigma = X.std(axis=0)
X_std = (X - mu) / sigma

print("Середні після стандартизації:")
print(X_std.mean(axis=0))

print("\nСтандартні відхилення:")
print(X_std.std(axis=0))

Середні після стандартизації:
[0.00000000e+00 0.00000000e+00 1.38777878e-17]

Стандартні відхилення:
[1. 1. 1.]


14.2. Лінійна модель без циклу

In [41]:
X = np.array([
    [1.0, 2.0],
    [2.0, 1.0],
    [3.0, 4.0]
])

w = np.array([0.5, -0.25])
b = 1.0

y_pred = X @ w + b

print(y_pred)

[1.   1.75 1.5 ]


14.3. Середньоквадратична помилка

In [42]:
y_true = np.array([1.2, 1.8, 2.5])
y_pred = np.array([1.0, 2.0, 2.3])

mse = np.mean((y_true - y_pred) ** 2)

print("MSE =", mse)

MSE = 0.04000000000000001


14.4. Евклідова відстань до набору об’єктів

In [43]:
X = np.array([
    [1., 2.],
    [4., 6.],
    [2., 3.]
])

q = np.array([1., 1.])

distances = np.linalg.norm(X - q, axis=1)

print(distances)

[1.         5.83095189 2.23606798]


15. Сортування, пошук і вибір

In [44]:
x = np.array([7, 2, 9, 2, 5])

print("sort:", np.sort(x))
print("argsort:", np.argsort(x))
print("unique:", np.unique(x))
print("where x >= 5:", np.where(x >= 5))
print("clip 3..7:", np.clip(x, 3, 7))

sort: [2 2 5 7 9]
argsort: [1 3 4 0 2]
unique: [2 5 7 9]
where x >= 5: (array([0, 2, 4]),)
clip 3..7: [7 3 7 3 5]


16. Збереження та завантаження масивів

In [45]:
X = np.arange(12).reshape(3, 4)

np.save("X.npy", X)
X_loaded = np.load("X.npy")

print("X_loaded.shape:", X_loaded.shape)
print(X_loaded)

np.savez_compressed(
    "dataset.npz",
    X=X,
    y=np.array([0, 1, 1])
)

data = np.load("dataset.npz")
print("\ndata['X'] =\n", data["X"])
print("data['y'] =", data["y"])

X_loaded.shape: (3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

data['X'] =
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
data['y'] = [0 1 1]


17. Числова стабільність і перевірка даних

In [46]:
x = np.array([1.0, np.nan, np.inf, -5.0])

print("isfinite:", np.isfinite(x))
print("Скінченні значення:", x[np.isfinite(x)])

isfinite: [ True False False  True]
Скінченні значення: [ 1. -5.]


Порівняння чисел із плаваючою комою

In [47]:
a = 0.1 + 0.2
b = 0.3

print("a == b:", a == b)
print("np.isclose(a, b):", np.isclose(a, b))

a == b: False
np.isclose(a, b): True


18. Узагальнюючий приклад: підготовка даних і лінійний прогноз

In [48]:
# 1. Вхідні дані: два фактори та цільова змінна
X = np.array([
    [10., 2.],
    [12., 3.],
    [15., 4.],
    [18., 5.],
    [20., 6.]
])

y = np.array([21., 25., 31., 36., 40.])

# 2. Фільтрація
mask = np.isfinite(X).all(axis=1) & np.isfinite(y)
X = X[mask]
y = y[mask]

# 3. Стандартизація ознак
mu = X.mean(axis=0)
sigma = X.std(axis=0)
X_std = (X - mu) / sigma

# 4. Додаємо стовпець одиниць для вільного члена
X_design = np.column_stack([
    np.ones(X_std.shape[0]),
    X_std
])

# 5. Оцінювання параметрів методом найменших квадратів
beta, *_ = np.linalg.lstsq(X_design, y, rcond=None)

# 6. Прогноз і MSE
y_pred = X_design @ beta
mse = np.mean((y - y_pred) ** 2)

print("beta =", beta)
print("y_pred =", y_pred)
print("MSE =", mse)

beta = [30.6         5.53172667  1.41421356]
y_pred = [21.1 25.1 30.6 36.1 40.1]
MSE = 0.03999999999999986


19. Підсумкові тренувальні завдання
Створіть матрицю X форми (5, 4) із випадкових чисел.
Обчисліть середнє та стандартне відхилення кожної ознаки.
Стандартизуйте матрицю через broadcasting.
Виберіть рядки, у яких значення першої ознаки додатне.
Додайте до матриці новий стовпець одиниць.
Створіть вектор ваг і обчисліть прогноз X @ w.
Для заданого y_true обчисліть MSE.
Перевірте, чи немає в масивах NaN або inf.

In [49]:
import numpy as np

rng = np.random.default_rng(42)

X = rng.normal(loc=5.0, scale=2.0, size=(5, 4))

mu = X.mean(axis=0)
sigma = X.std(axis=0)

X_std = (X - mu) / sigma

mask = X_std[:, 0] > 0
X_filtered = X_std[mask]

X_design = np.column_stack([
    np.ones(X_filtered.shape[0]),
    X_filtered
])

w = np.array([1.0, 0.5, -0.5, 0.2, 0.1])
y_pred = X_design @ w

y_true = rng.uniform(0, 2, size=y_pred.shape[0])
mse = np.mean((y_true - y_pred) ** 2)

is_valid = np.isfinite(X_design).all() and np.isfinite(y_true).all()

print("Відфільтрована матриця з одиницями (X_design):\n", X_design)
print("\nПрогноз (y_pred):", y_pred)
print("MSE =", mse)
print("Усі значення скінченні (без NaN/inf):", is_valid)

Відфільтрована матриця з одиницями (X_design):
 [[ 1.          0.63652765 -0.49447486  0.44941836  1.24634876]
 [ 1.          0.26468724 -0.28178693  0.89615322  1.00540443]
 [ 1.          0.36048346  1.97124793 -0.53083093 -1.41788899]
 [ 1.          0.71058354 -0.40220304  0.89287002 -0.21982453]]

Прогноз (y_pred): [ 1.78001981  1.55300818 -0.05333732  1.71298484]
MSE = 1.1915509557341675
Усі значення скінченні (без NaN/inf): True
